const router =require('express').Router()
const hardskill = require('../controllers/hardSkillsCtrl')
router.post('/ajoutHard',hardskill.create)
router.put('/updateHard/:id',hardskill.updateHardSkills)
router.get('/hardskills',hardskill.getAllHardSkillz)
router.delete('/deleteskills/:id',hardskill.deleteHardskill)
router.get('/gethard/:id',hardskill.getHardSkillsById)
const Listhard = require('../controllers/UserHardCntrl')
router.post('/affecterHard/:id',Listhard.create)
router.get('/listeHard',Listhard.getListHard)
router.get('/getHardList/:id',Listhard.findByUser)
router.get('/getNamehard/:id',Listhard.getNomSkills)
router.get('/getScorehard/:id',Listhard.findUsersScore)
router.get('/getSkillhard/:id',Listhard.findBySkill)
router.delete('/deleteSkillhard/:id',Listhard.delete)
/***user */
router.get('/users',hardskill.getUsers)
router.get('/users/:id',hardskill.getUserById)

module.exports=router