const ACTIONS = {
    LOGIN: 'LOGIN',
    GET_TOKEN: 'GET_TOKEN',
    GET_USER: 'GET_USER',
    GET_ALL_USERS: 'GET_ALL_USERS',
    GET_ALL_SKILLS : 'GET_ALL_SKILLS',
    GET_ALL_EVENTS : 'GET_ALL_EVENTS'

}

export default ACTIONS